version: '3'

services:
  api:
    build: .
    ports:
      - "5300:80"    
    environment:
      - MONGO_CONNECTION=mongodb://db:27017/gprofiles
      - ASPNETCORE_ENVIRONMENT=Development
  db:
    image: mvertes/alpine-mongo