name: Release image

on:
  push:
    branches: [ master ]
env:
  SERVICE_NAME: profiles

jobs:
  unit-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  push-image:
    needs: unit-test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $SERVICE_NAME

      - name: Login into github container regestry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to github container regestry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$SERVICE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag $SERVICE_NAME $IMAGE_ID
          docker push $IMAGE_ID
